### ISSUE TITLE
GH Actions are passing with flying colours even when they shouldn't

### ISSUE THREAD

**Issue by Karm** [Karm/mandrel-integration-tests#85]
e.g. https://github.com/Karm/mandrel-integration-tests/actions/runs/2054970693 

Should at least fail with 22.x JDK 17 due to:
 - fails on gdb https://github.com/graalvm/mandrel/issues/355
 - fails on #79

**Comment by Karm** [comment]
Check
```
      - uses: actions/cache@v2
        name: Mandrel installation cached
        id: cache_mandrel
        with:
          path: |
            ${{ github.workspace }}/${{ matrix.mandrel-version }}
          key: ${{ matrix.os }}-${{ matrix.mandrel-version }}
```
